<?php

namespace RHBundle\Repository;

/**
 * ModeacquisitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeacquisitionRepository extends \Doctrine\ORM\EntityRepository
{
}
