<?php

namespace DocumentBundle\Repository;

/**
 * CahierlaboratoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CahierlaboratoireRepository extends \Doctrine\ORM\EntityRepository
{
}
