<?php

namespace DocumentBundle\Repository;

/**
 * DocumentqualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentqualiteRepository extends \Doctrine\ORM\EntityRepository
{
}
