<?php

namespace DocumentBundle\Repository;

/**
 * DocumentmanagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentmanagementRepository extends \Doctrine\ORM\EntityRepository
{
}
