<?php

namespace DocumentBundle\Repository;

/**
 * FormeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormeRepository extends \Doctrine\ORM\EntityRepository
{
}
