<?php
/* Copyright 2016 C. Thubert */

namespace DocumentBundle\Repository;

/**
 * SupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * Trier les support selon leur nom, utilisé pour les formulaires.
     */
    public function trierParNom()
    {
        return $this->createQueryBuilder('s')
            ->orderBy('s.nom', 'ASC') ;
    }
}
