<?php

namespace DocumentBundle\Repository;

/**
 * TypedocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypedocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
