<?php
/* Copyright 2016 C. Thubert */

namespace DocumentBundle\Repository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends \Doctrine\ORM\EntityRepository
{
}
