
login_check:
    path: /login_check

logout:
    path: /logout

dechet_equipement:
    resource: "@DechetEquipementBundle/Controller"
    type: annotation

document:
    resource: "@DocumentBundle/Controller"
    type: annotation

utilisateur:
    resource: "@UtilisateurBundle/Controller"

rh:
    resource: "@RHBundle/Resources/config/routing.yml"
#    prefix:   /rh

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile