# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        UtilisateurBundle\Entity\Utilisateur: sha512
    
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: fos_userbundle
            form_login:
                login_path:  /login
                check_path: login_check
            logout:
                path: logout
                target: /
            remember_me:
                secret: %secret%
            
#            pattern:   ^/
#            form_login:
#                provider:     fos_userbundle
#                csrf_token_generator:   security.csrf.token_manager
#                login_path:  /login
##                login_path:  /
#                always_use_default_target_path: true
#                default_target_path:            /
#                target_path_parameter:          _target_path
#            logout:        true
#            anonymous:     true
#            remember_me:
#                secret:         %secret%
            #anonymous: ~
            
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/, roles: ROLE_USER } # TODO Uncomment to active authenticate !
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
