<?php
/* Copyright 2016 C. Thubert */

namespace DechetEquipementBundle\Repository;

/**
 * DechetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DechetRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * Trier les déchets selon leur nom, utilisé pour les formulaires.
     */
    public function trierParNom()
    {
        return $this->createQueryBuilder('d')
            ->orderBy('d.nom', 'ASC') ;
    }
}
