<?php

namespace DechetEquipementBundle\Repository;

/**
 * DechetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DechetRepository extends \Doctrine\ORM\EntityRepository
{
}
