<?php
/* Copyright 2016 C. Thubert */

namespace DechetEquipementBundle\Repository;

/**
 * ParcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * Trier les parcs selon leur nom, utilisé pour les formulaires.
     */
    public function trierParNom()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.nom', 'ASC') ;
    }
}
