<?php

namespace DechetEquipementBundle\Repository;

/**
 * ParcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcRepository extends \Doctrine\ORM\EntityRepository
{
}
