<?php

namespace DechetEquipementBundle\Repository;

/**
 * TypecontratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypecontratRepository extends \Doctrine\ORM\EntityRepository
{
}
