<?php
/* Copyright 2016 C. Thubert */

namespace UtilisateurBundle\Repository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * Trier les équipes selon leur nom, utilisé pour les formulaires.
     */
    public function trierParNom()
    {
        return $this->createQueryBuilder('e')
            ->orderBy('e.nom', 'ASC') ;
    }
}
