<?php
/* Copyright 2016 C. Thubert */

namespace UtilisateurBundle\Repository;

/**
 * StatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutRepository extends \Doctrine\ORM\EntityRepository
{
}
