<?php
/* Copyright 2016 C. Thubert */

namespace UtilisateurBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * Trier les utilisateurs selon leur nom, utilisé pour les formulaires.
     */
    public function trierParNom()
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.nom', 'ASC') ;
    }
}
